# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:57
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myfield',
            field=markdownx.models.MarkdownxField(default=' '),
            preserve_default=False,
        ),
    ]
