# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='comments',
            field=models.CharField(max_length=200),
        ),
    ]
