# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='myfield',
            new_name='body',
        ),
    ]
