# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 05:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171019_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
