# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 05:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postt'),
    ]

    operations = [
        migrations.AddField(
            model_name='postt',
            name='cont',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
            preserve_default=False,
        ),
    ]
