# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 05:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postt_cont'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postt',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
